name          'pimientadigital-phantomjs'
version       '1.0.0'
source        ''
author        'luis mayta'
license       'Mit'
summary       ''
description   ''
project_page  ''

dependency 'puppetlabs/stdlib'
