name          'hadenlabs-phantomjs'
version       '1.0.0'
source        ''
author        '@slovacus'
license       'Mit'
summary       ''
description   ''
project_page  'https://github.com/hadenlabs/puppet-module-phantomjs'

dependency 'puppetlabs/stdlib'
